{
 "title": "CyberPower UPS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device",
    "query": {
     "query": "label_values(upsBaseBatteryStatus,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Output Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsAdvanceOutputLoad{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Output Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsAdvanceOutputPower{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "upsAdvanceBatteryCapacity{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Run Time Remaining",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsAdvanceBatteryRunTimeRemaining{instance=\"$instance\"}/60/100"
    }
   ]
  },
  {
   "title": "Time on Battery",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "upsBaseBatteryTimeOnBattery{instance=\"$instance\"}/60/100"
    }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "upsAdvanceBatteryTemperature{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "upsAdvanceInputLineVoltage{instance=\"$instance\"}",
     "legendFormat": "Line Input"
    },
    {
     "expr": "upsAdvanceOutputVoltage{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "upsAdvanceInputFrequency{instance=\"$instance\"}",
     "legendFormat": "Input"
    },
    {
     "expr": "upsAdvanceOutputFrequency{instance=\"$instance\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "upsAdvanceOutputPower{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "upsAdvanceBatteryVoltage{instance=\"$instance\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Battery Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsAdvanceOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Total DC Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "expr": "upsAdvanceOutputCurrent{instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  }
 ]
}