[env]
AWS_ACCESS_KEY_ID = "{{ exec(command='op item get cloudflare --vault STONEHEDGES --fields AWS_ACCESS_KEY_ID --reveal') }}"
AWS_SECRET_ACCESS_KEY = "{{ exec(command='op item get cloudflare --vault STONEHEDGES --fields AWS_SECRET_ACCESS_KEY --reveal') }}"
