---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "${APP}-volsync-unlock"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "${APP}-volsync-unlock"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "${APP}-volsync-unlock"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "${APP}-volsync-unlock"
subjects:
  - kind: ServiceAccount
    name: "${APP}-volsync-unlock"
