---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kometa-secret
    template:
      engineVersion: v2
      data:
        config.yml: |
          libraries:
            Movies:
              collection_files:
                - default: universe
                - default: franchise
                - file: /config/collections/marvel.yml
                - file: /config/collections/spider-man.yml
              operations:
                mass_collection_mode: hide_items

          plex:
            url: http://plex-app.default.svc.cluster.local:32400
            token: {{ .PLEX_TOKEN }}

          radarr:
            url: http://radarr.default.svc.cluster.local
            token: {{ .RADARR__AUTH__APIKEY }}
            add_missing: true
            root_folder_path: /media/Library/movies
            quality_profile: Any

          tmdb:
            apikey: {{ .TMDB_APIKEY }}
            language: en
            region: US
  dataFrom:
    - extract:
        key: kometa
    - extract:
        key: radarr
