---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cert-exporter-doom
  namespace: default
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      cert-deploy:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "@daily"
          backoffLimit: 0
        containers:
          app:
            image:
              repository: neilpang/acme.sh
              tag: 3.1.3@sha256:3e7593e957e16edf357655bcd89164b81cd1634849df90e6dcb54891be9cc86b
            command: ['/bin/sh', '/scripts/export.sh']
            envFrom:
              - secretRef:
                  name: cert-exporter-doom-secret
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 128Mi
    persistence:
      scripts:
        name: cert-exporter-configmap
        enabled: true
        type: configMap
        globalMounts:
          - path: /scripts
            readOnly: true
      certificate-data:
        type: persistentVolumeClaim
        existingClaim: cert-exporter
        globalMounts:
          - path: /acme.sh/doom.${SECRET_INTERNAL_DOMAIN}
            subPath: doom.${SECRET_INTERNAL_DOMAIN}
