libraries:
  Movies:
    collection_files:
      - default: universe
      - default: franchise
      - file: /config/collections/marvel.yml
      - file: /config/collections/spider-man.yml
    operations:
      mass_collection_mode: hide_items

plex:
  url: http://plex.default.svc.cluster.local:32400
  token: <<PLEX_TOKEN>>

tmdb:
  apikey: <<TMDB_APIKEY>>
  language: en
  region: US
