#!/usr/bin/env bash
# Generate talos/pxe/dnsmasq.conf + boot.ipxe from the Talos node configs and
# .talos.env. Entry point is `just talos pxe-render` (or `just talos pxe-macs`).
#
#   render.sh          # write dnsmasq.conf + boot.ipxe
#   render.sh macs     # just print the "mac hostname" allow-list
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"

# mise exports these; fall back to .talos.env if run outside the mise env.
[ -n "${TALOS_VERSION:-}" ] || { set -a; . "$repo/.talos.env"; set +a; }
: "${TALOS_VERSION:?}" "${TALOS_SCHEMATIC_ID:?}"

# Emit "mac hostname" for every node that has a real MAC (skip REPLACE_WITH_MAC).
list_macs() {
  local f host mac
  for f in "$repo"/talos/nodes/*.yaml.j2; do
    host="$(sed -n 's/^[[:space:]]*hostname:[[:space:]]*//p' "$f" | head -1)"
    mac="$(grep -oiE '([0-9a-f]{2}:){5}[0-9a-f]{2}' "$f" | head -1 || true)"
    if [ -n "$mac" ]; then printf '%s %s\n' "$(printf '%s' "$mac" | tr 'A-Z' 'a-z')" "$host"; fi
  done
  return 0
}

if [ "${1:-}" = macs ]; then list_macs; exit 0; fi

allow="$(list_macs | awk '{printf "dhcp-host=%s,set:talos  # %s\n", $1, $2}')"
[ -n "$allow" ] || { echo "No configured MACs in talos/nodes" >&2; exit 1; }

# dnsmasq: proxyDHCP (coexists with UniFi, never assigns IPs) + TFTP, allow-listed.
{
  echo "# GENERATED by 'just talos pxe-render' — do not edit."
  echo "# proxyDHCP: coexists with UniFi (never assigns IPs, only answers PXE)."
  printf '%s\n' port=0 log-dhcp log-facility=-
  echo "dhcp-range=10.1.100.0,proxy"
  printf '%s\n' enable-tftp tftp-root=/srv/tftp tftp-no-fail
  echo "dhcp-match=set:efi64,option:client-arch,7"
  echo "dhcp-match=set:efi64,option:client-arch,9"
  echo "# --- allow-list (every talos/nodes/* with a configured MAC) ---"
  echo "$allow"
  echo "dhcp-boot=tag:talos,tag:efi64,ipxe.efi"
} > "$here/dnsmasq.conf"

# boot.ipxe: embedded into ipxe.efi; chains to the Factory → maintenance mode.
{
  echo "#!ipxe"
  echo "dhcp || echo DHCP failed"
  echo "echo Talos garage netboot -- Talos $TALOS_VERSION"
  echo "echo   MAC \${net0/mac}  IP \${net0/ip} -- chaining to Talos Factory"
  echo "chain --replace https://pxe.factory.talos.dev/pxe/$TALOS_SCHEMATIC_ID/$TALOS_VERSION/metal-amd64 || goto fail"
  printf '%s\n' ":fail" "echo Chain failed -- rebooting in 20s" "sleep 20" "reboot"
} > "$here/boot.ipxe"

echo "Rendered PXE config ($(printf '%s\n' "$allow" | grep -c '^dhcp-host=' || true) nodes) for Talos $TALOS_VERSION"
