---
name: Enable Tailscale SSH

on:
  workflow_dispatch: {}

jobs:
  enable-ssh:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Preflight (user and tailscale path)
        run: whoami && which tailscale || true

      - name: Enable Tailscale SSH
        run: echo "${{ secrets.SUDO_PASS }}" | sudo -S tailscale set --ssh

      - name: Verify Tailscale status
        run: echo "${{ secrets.SUDO_PASS }}" | sudo -S tailscale status
