---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: halfduplex-io-production
  namespace: network
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,network"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,network"
spec:
  secretName: halfduplex-io-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: halfduplex.io
  dnsNames:
    - halfduplex.io
    - "*.halfduplex.io"
